repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: poetry run isort --profile black .
        language: system
        types: [python]
    -   id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
